server:
  port: 8085
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/pubFinder
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
token:
  secret:
    key: 
super:
  user:
    mail: 

retry:
  config:
    maxAttempts: 3
    backoffDelay: 3000
